config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.connect 'lunches/find_by_date', :controller => 'lunches', :action => 'find_by_date'
  map.connect 'lunches/show_by_date', :controller => 'lunches', :action => 'show_by_date'
  map.connect 'lunches/:year/:month/:day',
              :controller => 'lunches',
              :action     => 'find_by_date',
              :year       => /\d{4}/,
              :month      => /\d{1,2}/,
              :day        => /\d{1,2}/

  map.connect 'orders/today', :controller => 'orders', :action => 'today'
  map.connect 'orders/find_by_date', :controller => 'orders', :action => 'find_by_date'
  map.connect 'orders/find_all_by_date', :controller => 'orders', :action => 'find_all_by_date'
  map.connect 'orders/find_by_month', :controller => 'orders', :action => 'find_by_month'
  map.connect 'orders/my', :controller => 'orders', :action => 'my'
  map.connect 'orders/monthly_report', :controller => 'orders', :action => 'monthly_report'
  map.connect 'orders/:year/:month',
              :controller => 'orders',
              :action     => 'find_by_month',
              :year       => /\d{4}/,
              :month      => /\d{1,2}/
  map.connect 'orders/:year/:month/:day',
              :controller => 'orders',
              :action     => 'find_all_by_date',
              :year       => /\d{4}/,
              :month      => /\d{1,2}/,
              :day        => /\d{1,2}/

  map.connect 'settings/lock_system', :controller => 'settings', :action => 'lock_system'
  map.connect 'settings/unlock_system', :controller => 'settings', :action => 'unlock_system'

  map.connect 'vendors/:id/notify_users',
              :controller => 'vendors',
              :action => 'notify_users',
              :id => /\d+/
  map.connect 'vendors/:id/mark_orders_complete',
              :controller => 'vendors',
              :action => 'mark_orders_complete',
              :id => /\d+/
  map.connect 'vendors/:id/mark_orders_new',
              :controller => 'vendors',
              :action => 'mark_orders_new',
              :id => /\d+/

  map.resource :account, :controller => "users"
  map.resource :user_session
  map.resources :users
  map.resources :lunches
  map.resources :orders
  map.resources :password_resets
  map.resource :settings
  map.resources :vendors

  map.root :controller => "user_sessions", :action => "new"
  map.login '/login', :controller => 'user_sessions', :action => 'new'
  map.logout '/logout', :controller => 'user_sessions', :action => 'destroy'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :user_groups
  has_many :orders
  has_many :lunches, :through => :orders
  
  acts_as_authentic

  validates_presence_of :login
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  
  named_scope :ordered_by_login, :order => "login ASC"
  named_scope :ordered_by_last_name,
              :order => "last_name ASC"

  def editor_ids
    ug = UserGroup.find_by_name('Usersadmin')
    # Return the user_ids associated to the user group plus this user's id
    ug.user_ids | [self.id]
  end
  
  def deliver_password_reset_instructions!
    reset_perishable_token!
    Notifier.deliver_password_reset_instructions(self)
  end

  def full_name
    [last_name, first_name].join(' ')
  end
  
  def refunded_lunches_for_date(date)
    orders.by_date(date).refundable_lunches
  end

  def can_order_lunch?(lunch)
    balance >= lunch.price_for_user(self) && lunch.date >= Date.current
  end
  
  def pay_for_order(order)
    update_attribute(:balance, balance - order.total)
  end
  
  def return_money_for_order(order)
    update_attribute(:balance, balance + order.total)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :fetch_user, :only => [:show, :edit, :update]

  def index
    @users = User.ordered_by_last_name
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
      add_lockdown_session_values(@user)
      redirect_to account_url
    else
      render :action => :new
    end
  end
  
  def show
    # redirect to /account if non-admin user tries to access others
    # Can't do this with lockdown as /account doesn't provide :id
    unless current_user_is_admin? or @user.id == current_user_id
      redirect_to account_url
    end
    store_location
  end

  def edit
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      respond_to do |format|
        format.html { redirect_back_or_default account_url }
        format.js
      end
    else
      render :action => :edit
    end
  end

  def destroy
    if current_user_is_admin?
      user = User.find(params[:id])
      user.destroy
      flash[:notice] = "User #{user.login} deleted!"
    end
    redirect_to users_path
  end

  private
  def fetch_user
    if params[:id]
        @user = User.find(params[:id])
    else
      @user = current_user # makes our views "cleaner" and more consistent
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.erb
<%= form.label :login %><br />
<%= form.text_field :login, :readonly => (not form.object.new_record?) %><br />
<br />
<%= form.label :password, form.object.new_record? ? nil : t('.change_password') %><br />
<%= form.password_field :password %><br />
<br />
<%= form.label :password_confirmation %><br />
<%= form.password_field :password_confirmation %><br />
<br />
<%= form.label :first_name %><br />
<%= form.text_field :first_name %><br />
<br />
<%= form.label :last_name %><br />
<%= form.text_field :last_name %><br />
<br />
<%= form.label :email %><br />
<%= form.text_field :email %><br />
<br />
<p>
  <%= form.label :email_notification_enabled, t('.notify_by_email') %>
  <%= form.check_box :email_notification_enabled %>
</p>
<% if current_user_is_admin? %>
  <%= form.label :user_groups %><br />
  <%= form.collection_select :user_group_ids, UserGroup.all(:conditions => ['name != ?', 'Administrators']), :id, :name, {}, {:multiple => true} %><br />
  <br />
<% end %>

app/views/users/edit.html.erb
<% if @user == current_user %>
  <h2><%= t '.edit_my_account' %></h2>
<% else %>
  <h2><%= t '.edit_users_account', :name => @user.login %></h2>
<% end %>

<% form_for @user, :url => user_path(@user) do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit t('.update_button') %>
<% end %>

<br /><%= link_to t('.my_profile_link'), user_path(@user) %>

app/views/users/index.html.erb
<h2><%= t '.user_list' %></h2>

<% unless @users.empty? %>
  <p>
  <table>
    <thead>
    <tr>
      <td align='center'><b><%= t '.name' %></b></td>
      <td><b><%= User.human_attribute_name(:login) %></b></td>
      <td colspan=2 align='center'><b><%= User.human_attribute_name(:balance) %></b></td>
    </tr>
    <thead>
    <tbody>
    <% @users.each do |u| %>
      <tr>
        <td><%= u.full_name %></td>
        <td><%= link_to "#{u.login}", user_path(u) %></td>
        <td id="user_<%= "#{u.id}" %>_balance"><%= to_currency u.balance %></td>
        <td>
          <% remote_form_for u, :url => user_path(u), :method => :put do |f| %>
            <%= f.text_field :balance, :size => 5, :id => "user_#{u.id}_balance_input" %>
            <%= f.submit t('.update_button'), :id => "user_#{u.id}_submit" %>
          <% end %>
        </td>
        <td><%= link_to t('.edit_account_link'), edit_user_path(u) %></td>
        <td><%= link_to t('.remove_account_link'), user_path(u), :method => :delete, :confirm => t('.sure_to_remove_account', :name => u.full_name) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  </p>
<% end %>

app/views/users/new.html.erb
<h2><%= t '.register' %></h2>

<% form_for @user, :url => account_path do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit t('.register_button') %>
<% end %>

app/views/users/show.html.erb
<p>
  <b><%= User.human_attribute_name(:login) %>:</b>
  <%=h @user.login %>
</p>

<p>
  <b><%= User.human_attribute_name(:first_name) %>:</b>
  <%=h @user.first_name %>
</p>

<p>
  <b><%= User.human_attribute_name(:last_name) %>:</b>
  <%=h @user.last_name %>
</p>

<p>
  <b><%= User.human_attribute_name(:email) %>:</b>
  <%=h @user.email %>
</p>

<p>
  <b><%= User.human_attribute_name(:balance) %>:</b>
  <%=h to_currency @user.balance %>
</p>

<%= link_to t('edit_link'), edit_user_path(@user) %>